Repository ItsDrike/SecurePy, pull requests merged in 2020-12, with the labels that each got.

#1 Tests
  .github/workflows/linting-tests.yml
  Pipfile
  securepy/config/config.py
  securepy/stdcapture.py
  securepy/timing.py
  setup.py
  tests/__init__.py
  tests/test_stdcapture.py
  tox.ini
Labels: enhancement

#2 Add possibility to simulate STDIN
  .gitignore
  README.md
  securepy/__init__.py
  securepy/restrictor.py
  securepy/stdio.py
  securepy/timing.py
  tests/test_stdcapture.py
Labels: priority: 2 - normal, type: feature

#3 Licence change
  LICENSE
Labels: priority: 0 - critical

#4 Use subprocess instead of time-limiting multiproc. separation
  README.md
  securepy/__init__.py
  securepy/executor.py
  securepy/limited_process.py
  securepy/restrictor.py
  securepy/security.py
  securepy/stdio.py
  securepy/timing.py
  tests/test_stdio.py
Labels: priority: 1 -high, status: WIP, type: feature

#7 Add issue auto-lable workflow
  .github/workflows/issues.yml
Labels: priority: 3 - low, type: feature

#6 Add pyright into GH CI
  .github/workflows/validation.yml
  pyrightconfig.json
Labels: priority: 2 - normal, type: feature

#8 Coverage
  .coveragerc
  .github/workflows/validation.yml
  .gitignore
  Pipfile
  Pipfile.lock
Labels: priority: 2 - normal, type: feature

#9 Test code on both linux and windows
  .github/workflows/validation.yml
  setup.py
Labels: priority: 1 -high, type: feature
